let headString="";
headString += "<meta charset=\"UTF-8\">";
headString += "<meta itemprop=\"legalName\" content=\"Southern Alberta Institute of Technology\">";
headString += "<meta itemprop=\"name\" content=\"SAIT\">";
headString += "<meta itemprop=\"url\" content=\"https:\/\/www.sait.ca\/\">";
headString += "<title>SAIT<\/title>";
headString += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
headString += "<meta name=\"description\" content=\"The Southern Alberta Institute of Technology (SAIT) offers programs to students with action-based learning to deliver the skills and knowledge employers demand.\">";
headString += "<meta name=\"author\" content=\"SAIT\">";
headString += "<meta name=\"keywords\" content=\"\">";
headString += "<meta name=\"robots\" content=\"\">";
headString += "<!-- Favicon -->";
headString += "<link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/apple-touch-icon-57x57.png\">";
headString += "<link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/apple-touch-icon-60x60.png\">";
headString += "<link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/apple-touch-icon-72x72.png\">";
headString += "<link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/apple-touch-icon-76x76.png\">";
headString += "<link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/apple-touch-icon-114x114.png\">";
headString += "<link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/apple-touch-icon-120x120.png\">";
headString += "<link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/apple-touch-icon-144x144.png\">";
headString += "<link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/apple-touch-icon-152x152.png\">";
headString += "<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/apple-touch-icon-180x180.png\">";
headString += "<link rel=\"icon\" type=\"image\/png\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/favicon-32x32.png\" sizes=\"32x32\">";
headString += "<link rel=\"icon\" type=\"image\/png\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/favicon-194x194.png\" sizes=\"194x194\">";
headString += "<link rel=\"icon\" type=\"image\/png\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/favicon-96x96.png\" sizes=\"96x96\">";
headString += "<link rel=\"icon\" type=\"image\/png\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/android-chrome-192x192.png\" sizes=\"192x192\">";
headString += "<link rel=\"icon\" type=\"image\/png\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/favicon-16x16.png\" sizes=\"16x16\">";
headString += "<link rel=\"manifest\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/manifest.json\">";
headString += "<link rel=\"mask-icon\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/safari-pinned-tab.svg\" color=\"#da291c\">";
headString += "<link rel=\"shortcut icon\" href=\"https:\/\/www.sait.ca\/assets\/prebuilt\/img\/favicon\/favicon.ico\">";
headString += "<meta name=\"msapplication-TileColor\" content=\"#da532c\">";
headString += "<meta name=\"msapplication-TileImage\" content=\"prebuilt\/img\/favicon\/mstile-144x144.png\">";
headString += "<meta name=\"msapplication-config\" content=\"prebuilt\/img\/favicon\/browserconfig.xml\">";
headString += "<meta name=\"theme-color\" content=\"#ffffff\">";
headString += "";
headString += "<!-- CSS from live site -->";
headString += "<link href='https:\/\/fonts.googleapis.com\/css?family=Titillium+Web:400,400italic,600,700' rel='stylesheet' type='text\/css'>";
headString += "<link href=\"https:\/\/events.time.ly\/opy9p2d\/theme.css?themeId=402594\" rel=\"stylesheet\">";
headString += "<link href=\"https:\/\/www.sait.ca\/prebuilt\/css\/tooltipster.min.css\" rel=\"stylesheet\">";
headString += "<link href=\"https:\/\/www.sait.ca\/prebuilt\/css\/dest\/screen.min.css\" rel=\"stylesheet\">";
headString += "<link href=\"https:\/\/www.sait.ca\/prebuilt\/css\/dest\/search.min.css\" rel=\"stylesheet\">";
headString += "<link href=\"https:\/\/www.sait.ca\/prebuilt\/css\/dest\/print.min.css\" rel=\"stylesheet\">";
headString += "<link href=\"https:\/\/www.sait.ca\/prebuilt\/css\/igx-styles.css?v=201909301020\" rel=\"stylesheet\">";
headString += "<link href=\"https:\/\/maxcdn.bootstrapcdn.com\/font-awesome\/4.7.0\/css\/font-awesome.min.css\" rel=\"stylesheet\">";
headString += "<link href=\"https:\/\/code.ionicframework.com\/ionicons\/2.0.1\/css\/ionicons.min.css\" rel=\"stylesheet\">";
headString += "<link href=\"https:\/\/www.sait.ca\/prebuilt\/css\/vendor\/remodal.min.css\" rel=\"stylesheet\">";
headString += "<link href=\"https:\/\/www.sait.ca\/prebuilt\/css\/vendor\/remodal-default-theme.min.css\" rel=\"stylesheet\">";
headString += "<link href=\"https:\/\/cdn.jsdelivr.net\/jquery.slick\/1.5.9\/slick.css\" rel=\"stylesheet\">";
headString += "";
headString += "<!-- New styles -->";
headString += "<link href=\"css\/screen.css\" rel=\"stylesheet\">";

document.write(headString);